[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "NODE_TLS_REJECT_UNAUTHORIZED=0 npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NODE_VERSION = "20.11.1" 