[build]
builder = "nixpacks"
buildCommand = "npm install -g yarn && yarn install && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/_health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NODE_VERSION = "20.11.1" 